---
abstract: 'Object-oriented methods of handling list of URLs.'
author:
  - 'Tore Aursand <toreau@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.64
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URL-List
requires:
  Carp: 1.26
  Domain::PublicSuffix: 0.09
  List::MoreUtils: 0.33
  Mouse: 1.11
  URI: 1.60
  namespace::autoclean: 0.13
version: 0.11
